# Generated by Django 5.0.2 on 2024-02-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(to="airport.crew"),
        ),
    ]
