# Generated by Django 5.0.2 on 2024-02-24 12:12

import airport.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_flight_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airplane_image_file_path
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taken_seats",
                to="airport.flight",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("seat", "row", "flight")},
        ),
    ]
